# --- General options --- #

# Name of website
title: DV8 IT Services

# Short description of your site
description: IT Consulting Done Differently

# --- Footer options --- #
author:
  name: Adam Kosseck

# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  email: "info@dv8it.com.au"